### ISSUE TITLE
Generate basic scaffolds for the project

### ISSUE THREAD

**Issue by harsh183** [dsc-umass/project-matching#18]
I this should be done this after the authentication is working. Once some scaffolding code is generated and the project has a decent number of files it is at a good point for more contributors to come in and get involved. 

The basic idea from the document so far is having the models be something like this
* Users (device model)
  - Name
  - Email
  - Skills/Interests (tags)
  - Resume(file upload - s3??)
  - Which orgs they belong to and their admin status via some join table
* Projects
  - organization_id
  - Has_many positions
  - skills/interests(tags)
* Organizations
  - Name
  - Email
  - Projects (belong_to)
  - Skills/Interests(tags)
* Positions (ex. Designer, Frontend/Backend) -
  - Project_id (belong_to) 
  - Title
  - Skills/Interests (tags)
  - User_id (if filled)

**Comment by Saakshaat** [comment]
@harsh183 does it make sense to just use strings for the skills/interests tags? 

I found [this](https://github.com/mbleigh/acts-as-taggable-on#actsastaggableon) too.

I think instead of all this, if we just added a separate Tag model with the following attributes:
- skills
- interests 
- parents (references) [for users, organizations, projects and positions]

**Comment by harsh183** [comment]
See https://github.com/dsc-umass/project-matching/issues/27

**Comment by harsh183** [comment]
> I think instead of all this, if we just added a separate Tag model with the following attributes:

Honestly why re-invent the wheel. The more we develop this feature, overtime I think we'll arrive at a really similar set as what the gem already does. Some of the example code on the Github page itself is *exactly* what we want.

```ruby
class User < ActiveRecord::Base
  acts_as_taggable_on :tags
  acts_as_taggable_on :skills, :interests #You can also configure multiple tag types per model
end

class UsersController < ApplicationController
  def user_params
    params.require(:user).permit(:name, :tag_list) ## Rails 4 strong params usage
  end
end
```

**Comment by harsh183** [comment]
We still have to create scaffolds for projects and positions.

**Comment by harsh183** [comment]
@Saakshaat so while Atrik was trying to add scaffolds for projects and positions we noticed that your branch didn't have everything actually and didn't have `organization.rb` in the `models/` folder but was there in the organization branch. 

But don't worry. This is easy to fix. The auto-merge can't happen, but you should be able to `git pull`, fix merge conflicts and submit a new PR once you're done. I noticed you're trying to do some sort of `acts_as_taggable` stuff which you might not have finished but I'd like to merge up your work soon so that the others can work on organization related things.
