### ISSUE TITLE
Setup Guard

### ISSUE THREAD

**Issue by harsh183** [dsc-umass/project-matching#19]
Featured in Hartl's book as well Guard basically watches your file changes and runs tests automatically. I don't think it's very high priority but it's nice to be set up.

**Comment by Saakshaat** [comment]
![Screen Shot 2020-07-26 at 9 52 02 PM](https://user-images.githubusercontent.com/49038287/88504870-c4a7f700-cf8a-11ea-8c8b-5d7e0c9425d5.png)
