### ISSUE TITLE
Setup Continious Integration

### ISSUE THREAD

**Issue by harsh183** [dsc-umass/project-matching#21]
Especially once after some basic test code is written. I think TravisCI, CircleCI, Github's setup are all worth looking into and we can pair this up with our code style checkers, test suites and pull requests.

**Comment by harsh183** [comment]
Configure Github+TravisCI (free for open source projects) to basically run all the install steps and run our test cases. 

https://guides.railsgirls.com/continuous-travis

https://medium.com/full-taxx/how-to-setup-travis-ci-for-a-rails-application-78a453963300

https://docs.travis-ci.com/user/languages/ruby/ (note the bundler caching thing)

**Comment by abhinavtripathy** [comment]
@AbhinandanPadhi @harsh183 There are 2 approaches with CI, either we use docker container within the CI(might be more difficult) or just setup rails and other dependencies like postgres within the CI. This is a good example: https://boringrails.com/articles/building-a-rails-ci-pipeline-with-github-actions/

**Comment by abhinavtripathy** [comment]
CI with docker, this is an option as well: https://help.github.com/en/actions/creating-actions/creating-a-docker-container-action
https://github.community/t/how-to-use-docker-compose-with-github-actions/16850

**Comment by harsh183** [comment]
Since we have docker already setup I'm leaning towards that approach.
