### ISSUE TITLE
Add tags for skills/areas of interest

### ISSUE THREAD

**Issue by harsh183** [dsc-umass/project-matching#27]
https://github.com/mbleigh/acts-as-taggable-on could be a good starting point. 

The way I see it as that Users, Projects and Organizations will all have associated tags, and we can use weighted averages (or any other matching algorithm) to figure out matching people. Of course I think this will take some experimentation and thinking over to get right but from the implementation point of view this gem can provide us with a good amount of that.

**Comment by harsh183** [comment]
@Saakshaat you've added the tagging for some models, do you think you can add some more as well as add a few tests just verifying everything is there?

**Comment by Saakshaat** [comment]
As far as tags are concerned, right now I can only think of skills.
For organizations, it wouldn't make sense to associate skills but perhaps some other tags could work.

**Comment by harsh183** [comment]
I think what can happen is an project can have skills as well plus showing all the tags of their children. I think there can be scenarios where clubs may put up projects for example but don't really list specific positions. Or there can be clubs that don't list any projects at all but just create a club page.

**Comment by Saakshaat** [comment]
[This](https://medium.com/le-wagon/acts-as-taggable-on-tutorial-with-rails-5-417a862804b6) medium article is helping me understand the implementation. Leaving this here for future references.

**Comment by Saakshaat** [comment]
mbleigh's [tutorial on his wiki](https://github.com/mbleigh/acts-as-taggable-on/wiki/Tutorial-for-Posts) helped me integrate tags. 

Leaving this here for future references.
