### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Saakshaat** [dsc-umass/project-matching#4]
#### Problem
We need to figure out a way to decide how we go about authenticating a user and organization.

#### Solution
The [official Rails guide](https://guides.rubyonrails.org/) mentions some solutions like [AuthLogic](https://github.com/binarylogic/authlogic#1a-overview) during their discussion about [user validation](https://guides.rubyonrails.org/getting_started.html#basic-authentication). 

#### Consideration
_AuthLogic_ and most other auth solutions would involve hashing and storing the user's credentials in a database. But it is always a security hazard to store user credentials even if we hash them. We should look into OAuth providers such as [Google Auth](https://medium.com/@amoschoo/google-oauth-for-ruby-on-rails-129ce7196f35) and [GitHub Auth](https://github.com/omniauth/omniauth-github).

**Comment by harsh183** [comment]
Look into [devise](https://github.com/heartcombo/devise) which I feel hits all these needs plus a lot more.

Here are some good guides on starting out:
* https://guides.railsgirls.com/devise
* https://www.sitepoint.com/devise-authentication-in-depth/

The [UMass Hackathon Dashboard](https://github.com/fuseumass/dashboard) seems like a good use case example at first glance. Worth taking a look as a reference example.

**Comment by Saakshaat** [comment]
What if we stored passwords in plain text just like a big name company, which shan't be named?
hahah jk....unless?

**Comment by AtrikDas** [comment]
I'll implement the authentication with devise.
