### ISSUE TITLE
Configure Virtual Environment

### ISSUE THREAD

**Issue by Saakshaat** [dsc-umass/project-matching#55]
We need to set up a virtual environment so that all non-gem dependencies come packed, saving any contributors the time and effort to install them individually. 

For instance, we faced an issue with not having `docker-compose` locally which could be possibly sorted by setting up 

We already have a Gemfile, using which `bundler` sets up all the required dependencies that are available as `gems`, so we need to either look for gems related to all the configuration related dependencies or look for an alternate to be used with `bundler`.

Relevant Links
-
- [Using Virtual Environments - Ruby I](https://www.develves.net/blogs/asd/2016-03-17-using-virtual-environments-ruby-1/)
- [Stackoverflow Post](https://stackoverflow.com/questions/486995/ruby-equivalent-of-virtualenv) 
- [Reddit](https://www.reddit.com/r/ruby/comments/2qc7sx/anything_like_virtualenv_python_for_ruby/)
- [Fotsies Technology Blog](https://fgimian.github.io/blog/2012/12/08/setting-up-virtual-development-environments-for-ruby/)

**Comment by harsh183** [comment]
Other than PostgreSQL do we have any other dependencies. I think the `Dockerfile` and setup bash scripts meet this purpose. 

Are we using anything else?

**Comment by harsh183** [comment]
Honestly I don't this is worthwhile because gemspec, virtual envs come from an era pre `bundler`. Dockerfiles solve the issue of non ruby dependencies like PostgreSQL (which seems to be our only one). I think it's better to figure out how the `docker-compose` works than dealing with this.
